define({
        placeHolder: "",

        regAccount: "Registro - Crear Cuenta",
        lbConfirAccount: "Confirmar",
        compulsoryFields: "Los campos marcados con <span class='asterisk-form-app'>*</span> son campos obligatorios",
        userName: "Usuario",
        eMailID: "E-Mail ID",
        altEMailID: "E-Mail ID Alternativo",
        phone:"Teléfono",
        countryCode:"Código País",
        cityCode:"Código Ciudad",
        phoneNumber:"Número",
        postalAdress:"Código Postal",
        country:"País",
        password:"Contraseña",
        repeatPassword:"Repetir Contraseña",
        acceptTerms:"Acepto los ",
        termsUse:"<label for='terms'>Acepta los </label> <a href=''#'>Terminos de Uso</a>",
        submitContinue:"Continuar >>",
        submitReset:"Limpiar",
        submitBack: "Regresar",
        formInvalid:'Formulario contiene datos invalidos. Por favor corregir',
        termsNotAccepted:'No ha aceptado los Terminos de Uso',
        formValid:'Datos validados, seleccione Ok para confirmar registro',
        invalidMessagePass: "La segunda contraseña no es igual a la primera",
        invalidMessageTerms: "Acepte los terminos de uso"
});