define("example/nls/es/CreateAccountWidget",
({
	invalidMessage: "El valor especificado no es válido.",
	missingMessage: "Este valor es necesario.",
	rangeMessage: "Este valor está fuera del intervalo.",
	formTitle: "Registrarse - Crear Cuenta",
	confirmTitle: "Confirmar - Crear Cuenta",
	fieldMarkedWith: 'Campos marcados con',
	areCompulsoryFields: 'son requeridos.',
	name: 'Nombre',
	accountInfo: 'Información de la cuenta',
	username: 'Nombre de usuario',
	emailId: 'Correo electrónico',
	alternativeEmailId: 'Correo electrónico alternativo',
	yourPhone: 'Teléfono',
	countryCode: 'Código país',
	cityCode: 'Código Ciudad',
    address: 'Dirección',
    secondaryAddress: 'Otra Dirección',
    city: 'Ciudad',
    state: 'Estado',
    zip: 'Zip',
    yourBillingAddress: 'Dirección de Facturación',
    contactInfoSameAsBilling: 'Mi dirección de facturacón será la misma',
	phoneNumber: 'Número de Teléfono',
	yourPostalAddress: 'Dirección Postal',
	country: 'País',
	selectOne: 'Seleccionar',
	password: 'Contraseña',
	reEnterPassword: 'Repetir Contraseña',
	iAcceptThe: 'Accepto los',
	termsOfUse: 'Términos de uso',
	lContinue: 'Continuar',
	reset: 'Cancelar',
    congratulations: 'Felicitaciones',
    lBack: 'Regresar'
})
);
