define("example/nls/en/CreateAccountWidget",
({
	formTitle: "Register - Create Account",
    confirmTitle: "Confirm - Create Account",
	fieldMarkedWith: 'Field marked with',
	areCompulsoryFields: 'are compulsory fields.',
	username: 'Username',
	accountInfo: 'Account Information',
	name: 'Name',
	emailId: 'E-Mail ID',
	alternativeEmailId: 'Alternative E-Mail ID',
	yourPhone: 'Your Phone',
	countryCode: 'Country Code',
	cityCode: 'City Code',
    address: 'Address',
    secondaryAddress: 'Other Address',
    city: 'City',
    state: 'State',
    zip: 'Zip',
    yourBillingAddress: 'Billing Address',
    contactInfoSameAsBilling: 'My contact information is the same as my billing address',
	phoneNumber: 'Phone Number',
	yourPostalAddress: 'Your Postal Address',
	country: 'Country',
	selectOne: 'Select One',
	password: 'Password',
	reEnterPassword: 'Re - Enter Password',
	iAcceptThe: 'I accept the',
	termsOfUse: 'Terms of use',
	lContinue: 'Continue',
	reset: 'Reset',
	congratulations: 'Congratulations',
	lBack: 'Back'
})
);
