define("example/nls/en/CreateAccountWidget",
({
	invalidMessage: "El valor especificado no es válido.",
	missingMessage: "Este valor es necesario.",
	rangeMessage: "Este valor está fuera del intervalo.",
	formTitle: "Register - Create Account",
	fieldMarkedWith: 'Field marked with',
	areCompulsoryFields: 'are compulsory fields.',
	username: 'Username',
	emailId: 'E-Mail ID',
	alternativeEmailId: 'Alternative E-Mail ID',
	yourPhone: 'Your Phone',
	countryCode: 'Country Code',
	cityCode: 'City Code',
	phoneNumber: 'Phone Number',
	yourPostalAddress: 'Your Postal Address',
	country: 'Country',
	selectOne: 'Select One',
	password: 'Password',
	reEnterPassword: 'Re - Enter Password',
	iAcceptThe: 'I accept the',
	termsOfUse: 'Terms of use',
	lContinue: 'Continue',
	reset: 'Reset'
})
);
